# Generated by Django 4.2.7 on 2023-12-07 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='users',
            field=models.ManyToManyField(related_name='city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='users',
            field=models.ManyToManyField(related_name='country', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('users', models.ManyToManyField(related_name='countries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('wiki_page', models.TextField()),
                ('city_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='weather.usercountry')),
                ('users', models.ManyToManyField(related_name='cities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'unique_together': {('lat', 'lon')},
            },
        ),
    ]
