# Generated by Django 4.2.7 on 2023-12-07 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_users_alter_country_users_usercountry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='users',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
