# Generated by Django 4.2.7 on 2023-12-07 22:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0003_remove_country_users_delete_city_delete_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCity',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='UserCountry',
            new_name='Country',
        ),
    ]
