# Generated by Django 4.2.7 on 2023-12-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_rename_usercity_city_rename_usercountry_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image_url',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
