# Generated by Django 4.2.7 on 2023-12-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_city_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='users',
        ),
    ]
